interface EmojiData {
  character: string;
  name: string;
  keywords: string[];
}

interface EmojiCategory {
  name: string;
  icon: string;
  emojis: EmojiData[];
}

class EmojiService {
  private categories: EmojiCategory[] = [];
  private isLoaded = false;

  // Complete offline emoji database (Facebook/Instagram style)
  private emojiDatabase: { [key: string]: EmojiData[] } = {
    smileys: [
      { character: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'joy', 'grin'] },
      { character: '😃', name: 'grinning face with big eyes', keywords: ['smile', 'happy', 'joy', 'haha'] },
      { character: '😄', name: 'grinning face with smiling eyes', keywords: ['smile', 'happy', 'joy', 'laugh'] },
      { character: '😁', name: 'beaming face with smiling eyes', keywords: ['smile', 'happy', 'joy'] },
      { character: '😆', name: 'grinning squinting face', keywords: ['happy', 'joy', 'lol', 'satisfied'] },
      { character: '😅', name: 'grinning face with sweat', keywords: ['hot', 'happy', 'laugh', 'sweat', 'relief'] },
      { character: '🤣', name: 'rolling on the floor laughing', keywords: ['lol', 'laughing', 'funny', 'rofl'] },
      { character: '😂', name: 'face with tears of joy', keywords: ['cry', 'tears', 'joy', 'laugh'] },
      { character: '🙂', name: 'slightly smiling face', keywords: ['smile', 'happy'] },
      { character: '🙃', name: 'upside down face', keywords: ['silly', 'weird', 'upside down'] },
      { character: '😉', name: 'winking face', keywords: ['wink', 'flirt', 'joke'] },
      { character: '😊', name: 'smiling face with smiling eyes', keywords: ['smile', 'happy', 'flushed', 'crush', 'embarrassed', 'shy', 'joy'] },
      { character: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent'] },
      { character: '🥰', name: 'smiling face with hearts', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'crush'] },
      { character: '😍', name: 'smiling face with heart eyes', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'crush', 'heart eyes'] },
      { character: '🤩', name: 'star struck', keywords: ['smile', 'starry', 'eyes', 'grinning'] },
      { character: '😘', name: 'face blowing a kiss', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation', 'kiss'] },
      { character: '😗', name: 'kissing face', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation'] },
      { character: '☺️', name: 'smiling face', keywords: ['smile', 'happy', 'flushed', 'crush', 'embarrassed', 'shy', 'joy'] },
      { character: '😚', name: 'kissing face with closed eyes', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation'] },
      { character: '😙', name: 'kissing face with smiling eyes', keywords: ['love', 'like', 'affection', 'valentines', 'infatuation'] },
      { character: '🥲', name: 'smiling face with tear', keywords: ['proud', 'cry', 'happy'] },
      { character: '😋', name: 'face savoring food', keywords: ['happy', 'joy', 'tongue', 'smile', 'face', 'silly', 'yummy', 'nom', 'delicious', 'savouring'] },
      { character: '😛', name: 'face with tongue', keywords: ['prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue', 'silly'] },
      { character: '😜', name: 'winking face with tongue', keywords: ['prank', 'childish', 'playful', 'mischievous', 'smile', 'wink', 'tongue'] },
      { character: '🤪', name: 'zany face', keywords: ['goofy', 'wacky', 'crazy', 'silly'] },
      { character: '😝', name: 'squinting face with tongue', keywords: ['prank', 'playful', 'mischievous', 'smile', 'tongue'] },
      { character: '🤑', name: 'money mouth face', keywords: ['rich', 'money', 'greedy', 'dollar'] },
      { character: '🤗', name: 'hugging face', keywords: ['hug', 'thank you', 'thanks'] },
      { character: '🤭', name: 'face with hand over mouth', keywords: ['quiet', 'whoops', 'surprise', 'secret'] },
      { character: '🤫', name: 'shushing face', keywords: ['quiet', 'shush', 'secret'] },
      { character: '🤔', name: 'thinking face', keywords: ['hmm', 'think', 'consider'] },
      { character: '🤐', name: 'zipper mouth face', keywords: ['sealed', 'zipper', 'secret', 'silence'] },
      { character: '🤨', name: 'face with raised eyebrow', keywords: ['suspicious', 'sceptical'] },
      { character: '😐', name: 'neutral face', keywords: ['indifference', 'meh', 'whatever'] },
      { character: '😑', name: 'expressionless face', keywords: ['indifferent', 'blank', 'meh'] },
      { character: '😶', name: 'face without mouth', keywords: ['silence', 'speechless'] },
      { character: '😶‍🌫️', name: 'face in clouds', keywords: ['confused', 'dizzy', 'lost'] },
      { character: '😏', name: 'smirking face', keywords: ['smug', 'sly', 'suggestive'] },
      { character: '😒', name: 'unamused face', keywords: ['indifference', 'bored', 'straight face', 'serious', 'sarcasm'] },
      { character: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'frustrated'] },
      { character: '😬', name: 'grimacing face', keywords: ['grimace', 'teeth'] },
      { character: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief', 'tired'] },
      { character: '🤥', name: 'lying face', keywords: ['liar', 'pinocchio'] },
      { character: '😔', name: 'pensive face', keywords: ['sad', 'depressed', 'upset'] },
      { character: '😪', name: 'sleepy face', keywords: ['tired', 'rest', 'nap'] },
      { character: '🤤', name: 'drooling face', keywords: ['drooling'] },
      { character: '😴', name: 'sleeping face', keywords: ['tired', 'sleepy', 'night', 'zzz'] },
      { character: '😷', name: 'face with medical mask', keywords: ['sick', 'ill', 'disease', 'covid'] },
      { character: '🤒', name: 'face with thermometer', keywords: ['sick', 'temperature', 'thermometer', 'cold', 'fever'] },
      { character: '🤕', name: 'face with head bandage', keywords: ['injured', 'clumsy', 'bandage', 'hurt'] },
      { character: '🤢', name: 'nauseated face', keywords: ['sick', 'barf', 'disgusted', 'nausea'] },
      { character: '🤮', name: 'face vomiting', keywords: ['sick', 'barf', 'disgusted', 'nausea', 'puke', 'throw up'] },
      { character: '🤧', name: 'sneezing face', keywords: ['gesundheit', 'sneeze', 'sick', 'allergy'] },
      { character: '🥵', name: 'hot face', keywords: ['hot', 'heat', 'sweating'] },
      { character: '🥶', name: 'cold face', keywords: ['cold', 'freezing', 'ice'] },
      { character: '🥴', name: 'woozy face', keywords: ['dizzy', 'intoxicated', 'tipsy', 'wavy'] },
      { character: '😵', name: 'knocked out face', keywords: ['dizzy', 'spent', 'unconscious'] },
      { character: '😵‍💫', name: 'face with spiral eyes', keywords: ['confused', 'dizzy', 'hypnotized'] },
      { character: '🤯', name: 'exploding head', keywords: ['mind blown', 'shocked'] },
      { character: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'hat'] },
      { character: '🥳', name: 'partying face', keywords: ['party', 'celebration', 'birthday'] },
      { character: '🥸', name: 'disguised face', keywords: ['disguise', 'pretend', 'brows', 'glasses', 'moustache'] },
      { character: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'smile', 'summer', 'beach', 'sunglass'] },
      { character: '🤓', name: 'nerd face', keywords: ['nerdy', 'geek', 'dork'] },
      { character: '🧐', name: 'face with monocle', keywords: ['stuffy', 'wealthy'] },
      { character: '😕', name: 'confused face', keywords: ['confused', 'worry', 'upset'] },
      { character: '😟', name: 'worried face', keywords: ['concern', 'nervous', 'worried'] },
      { character: '🙁', name: 'slightly frowning face', keywords: ['disappointed', 'sad', 'upset'] },
      { character: '☹️', name: 'frowning face', keywords: ['upset', 'sad'] },
      { character: '😮', name: 'face with open mouth', keywords: ['surprise', 'impressed', 'wow'] },
      { character: '😯', name: 'hushed face', keywords: ['woo', 'shh'] },
      { character: '😲', name: 'astonished face', keywords: ['xox', 'surprised', 'poisoned'] },
      { character: '😳', name: 'flushed face', keywords: ['dazed', 'drunk', 'red', 'ridiculed', 'surprise'] },
      { character: '🥺', name: 'pleading face', keywords: ['puppy dog eyes', 'sad', 'pleading'] },
      { character: '😦', name: 'frowning face with open mouth', keywords: ['aw', 'what'] },
      { character: '😧', name: 'anguished face', keywords: ['stunned', 'nervous'] },
      { character: '😨', name: 'fearful face', keywords: ['scared', 'terrified', 'nervous'] },
      { character: '😰', name: 'anxious face with sweat', keywords: ['worried', 'nervous', 'sweat'] },
      { character: '😥', name: 'sad but relieved face', keywords: ['phew', 'sweat', 'nervous'] },
      { character: '😢', name: 'crying face', keywords: ['sad', 'tear', 'cry', 'upset'] },
      { character: '😭', name: 'loudly crying face', keywords: ['sad', 'cry', 'bawling', 'sobbing', 'tear'] },
      { character: '😱', name: 'face screaming in fear', keywords: ['horror', 'shocked'] },
      { character: '😖', name: 'confounded face', keywords: ['confused', 'sick', 'unwell', 'oops', 'doh'] },
      { character: '😣', name: 'persevering face', keywords: ['sick', 'no', 'upset', 'oops'] },
      { character: '😞', name: 'disappointed face', keywords: ['sad', 'upset', 'depressed'] },
      { character: '😓', name: 'downcast face with sweat', keywords: ['hard work', 'sweat', 'defeat'] },
      { character: '😩', name: 'weary face', keywords: ['tired', 'sleepy', 'sad', 'frustrated', 'upset'] },
      { character: '😫', name: 'tired face', keywords: ['sick', 'whine', 'upset', 'frustrated'] },
      { character: '🥱', name: 'yawning face', keywords: ['tired', 'sleepy'] },
      { character: '😤', name: 'face with steam from nose', keywords: ['gas', 'phew', 'proud', 'pride'] },
      { character: '😡', name: 'pouting face', keywords: ['angry', 'mad', 'hate', 'despise'] },
      { character: '😠', name: 'angry face', keywords: ['mad', 'annoyed', 'frustrated'] },
      { character: '🤬', name: 'face with symbols on mouth', keywords: ['swearing', 'cursing'] },
      { character: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'horns'] },
      { character: '👿', name: 'angry face with horns', keywords: ['devil', 'angry', 'horns'] },
      { character: '💀', name: 'skull', keywords: ['dead', 'skeleton', 'creepy', 'death'] },
      { character: '☠️', name: 'skull and crossbones', keywords: ['poison', 'danger', 'deadly', 'scary', 'death'] },
    ],
    people: [
      { character: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'goodbye', 'hi'] },
      { character: '🤚', name: 'raised back of hand', keywords: ['fingers', 'raised', 'backhand'] },
      { character: '🖐️', name: 'hand with fingers splayed', keywords: ['hand', 'fingers', 'palm'] },
      { character: '✋', name: 'raised hand', keywords: ['fingers', 'stop', 'highfive', 'palm', 'ban'] },
      { character: '🖖', name: 'vulcan salute', keywords: ['hand', 'fingers', 'spock', 'star trek'] },
      { character: '👌', name: 'OK hand', keywords: ['fingers', 'limbs', 'perfect', 'ok', 'okay'] },
      { character: '🤌', name: 'pinched fingers', keywords: ['sarcastic', 'italian', 'chef kiss', 'fingertips'] },
      { character: '🤏', name: 'pinching hand', keywords: ['tiny', 'small', 'size'] },
      { character: '✌️', name: 'victory hand', keywords: ['fingers', 'ohyeah', 'hand', 'peace', 'victory', 'two'] },
      { character: '🤞', name: 'crossed fingers', keywords: ['good', 'lucky'] },
      { character: '🤟', name: 'love you gesture', keywords: ['hand', 'fingers', 'gesture'] },
      { character: '🤘', name: 'sign of the horns', keywords: ['hand', 'fingers', 'evil eye', 'sign of horns', 'rock on'] },
      { character: '🤙', name: 'call me hand', keywords: ['hands', 'gesture'] },
      { character: '👈', name: 'backhand index pointing left', keywords: ['direction', 'fingers', 'hand', 'left'] },
      { character: '👉', name: 'backhand index pointing right', keywords: ['direction', 'fingers', 'hand', 'right'] },
      { character: '👆', name: 'backhand index pointing up', keywords: ['direction', 'fingers', 'hand', 'up'] },
      { character: '🖕', name: 'middle finger', keywords: ['hand', 'fingers', 'rude', 'middle', 'flipping'] },
      { character: '👇', name: 'backhand index pointing down', keywords: ['direction', 'fingers', 'hand', 'down'] },
      { character: '☝️', name: 'index pointing up', keywords: ['hand', 'fingers', 'direction', 'up'] },
      { character: '👍', name: 'thumbs up', keywords: ['thumbsup', 'yes', 'awesome', 'good', 'agree', 'accept', 'cool', 'hand', 'like'] },
      { character: '👎', name: 'thumbs down', keywords: ['thumbsdown', 'no', 'dislike', 'hand'] },
      { character: '✊', name: 'raised fist', keywords: ['fingers', 'hand', 'grasp'] },
      { character: '👊', name: 'oncoming fist', keywords: ['angry', 'violence', 'fist', 'hit', 'attack', 'hand'] },
      { character: '🤛', name: 'left-facing fist', keywords: ['hand', 'fistbump'] },
      { character: '🤜', name: 'right-facing fist', keywords: ['hand', 'fistbump'] },
      { character: '👏', name: 'clapping hands', keywords: ['praise', 'applause', 'congrats', 'yay'] },
      { character: '🙌', name: 'raising hands', keywords: ['gesture', 'hooray', 'yea', 'celebration', 'hands'] },
      { character: '👐', name: 'open hands', keywords: ['fingers', 'butterfly', 'hands', 'open'] },
      { character: '🤲', name: 'palms up together', keywords: ['hands', 'gesture', 'cupped', 'prayer'] },
      { character: '🤝', name: 'handshake', keywords: ['agreement', 'shake'] },
      { character: '🙏', name: 'folded hands', keywords: ['please', 'hope', 'wish', 'namaste', 'highfive'] },
      { character: '✍️', name: 'writing hand', keywords: ['lower left ballpoint pen', 'stationery', 'write', 'compose'] },
      { character: '💅', name: 'nail polish', keywords: ['beauty', 'manicure', 'finger', 'fashion', 'nail'] },
      { character: '🤳', name: 'selfie', keywords: ['camera', 'phone'] },
      { character: '💪', name: 'flexed biceps', keywords: ['arm', 'flex', 'hand', 'summer', 'strong', 'biceps'] },
      { character: '🦾', name: 'mechanical arm', keywords: ['accessibility', 'prosthetic'] },
      { character: '🦿', name: 'mechanical leg', keywords: ['accessibility', 'prosthetic'] },
      { character: '🦵', name: 'leg', keywords: ['kick', 'limb'] },
      { character: '🦶', name: 'foot', keywords: ['kick', 'stomp'] },
      { character: '👂', name: 'ear', keywords: ['face', 'hear', 'sound', 'listen'] },
      { character: '🦻', name: 'ear with hearing aid', keywords: ['accessibility', 'hard of hearing'] },
      { character: '👃', name: 'nose', keywords: ['smell', 'sniff'] },
      { character: '🧠', name: 'brain', keywords: ['smart', 'intelligent'] },
      { character: '🫀', name: 'anatomical heart', keywords: ['health', 'heartbeat'] },
      { character: '🫁', name: 'lungs', keywords: ['breath', 'oxygen'] },
      { character: '🦷', name: 'tooth', keywords: ['teeth', 'dentist'] },
      { character: '🦴', name: 'bone', keywords: ['skeleton'] },
      { character: '👀', name: 'eyes', keywords: ['look', 'watch', 'stalk', 'peek', 'see'] },
      { character: '👁️', name: 'eye', keywords: ['face', 'look', 'see', 'watch', 'stare'] },
      { character: '👅', name: 'tongue', keywords: ['mouth', 'playful'] },
      { character: '👄', name: 'mouth', keywords: ['mouth', 'kiss'] },
    ],
    animals: [
      { character: '🐶', name: 'dog face', keywords: ['animal', 'friend', 'nature', 'woof', 'puppy', 'pet', 'faithful'] },
      { character: '🐱', name: 'cat face', keywords: ['animal', 'meow', 'pet', 'cats'] },
      { character: '🐭', name: 'mouse face', keywords: ['animal', 'nature', 'cheese wedge', 'rodent'] },
      { character: '🐹', name: 'hamster', keywords: ['animal', 'nature'] },
      { character: '🐰', name: 'rabbit face', keywords: ['animal', 'nature', 'pet', 'spring', 'magic', 'bunny'] },
      { character: '🦊', name: 'fox', keywords: ['animal', 'nature', 'red'] },
      { character: '🐻', name: 'bear', keywords: ['animal', 'nature', 'wild'] },
      { character: '🐼', name: 'panda', keywords: ['animal', 'nature', 'panda'] },
      { character: '🐻‍❄️', name: 'polar bear', keywords: ['animal', 'arctic'] },
      { character: '🐨', name: 'koala', keywords: ['animal', 'nature'] },
      { character: '🐯', name: 'tiger face', keywords: ['animal', 'cat', 'danger', 'wild', 'nature', 'roar'] },
      { character: '🦁', name: 'lion', keywords: ['animal', 'nature', 'proud'] },
      { character: '🐮', name: 'cow face', keywords: ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'] },
      { character: '🐷', name: 'pig face', keywords: ['animal', 'oink', 'nature'] },
      { character: '🐽', name: 'pig nose', keywords: ['animal', 'oink'] },
      { character: '🐸', name: 'frog', keywords: ['animal', 'nature', 'croak', 'toad'] },
      { character: '🐵', name: 'monkey face', keywords: ['animal', 'nature', 'circus'] },
      { character: '🙈', name: 'see no evil monkey', keywords: ['monkey', 'animal', 'nature', 'haha'] },
      { character: '🙉', name: 'hear no evil monkey', keywords: ['monkey', 'animal', 'nature'] },
      { character: '🙊', name: 'speak no evil monkey', keywords: ['monkey', 'animal', 'nature', 'omg'] },
      { character: '🐒', name: 'monkey', keywords: ['animal', 'nature', 'banana', 'circus'] },
      { character: '🐔', name: 'chicken', keywords: ['animal', 'cluck', 'nature', 'bird'] },
      { character: '🐧', name: 'penguin', keywords: ['animal', 'nature'] },
      { character: '🐦', name: 'bird', keywords: ['animal', 'nature', 'fly', 'tweet', 'spring'] },
      { character: '🐤', name: 'baby chick', keywords: ['animal', 'chicken', 'bird'] },
      { character: '🐣', name: 'hatching chick', keywords: ['animal', 'chicken', 'egg', 'born', 'baby', 'bird'] },
      { character: '🐥', name: 'front-facing baby chick', keywords: ['animal', 'chicken', 'baby', 'bird'] },
      { character: '🦆', name: 'duck', keywords: ['animal', 'nature', 'bird', 'mallard'] },
      { character: '🦅', name: 'eagle', keywords: ['animal', 'nature', 'bird'] },
      { character: '🦉', name: 'owl', keywords: ['animal', 'nature', 'bird', 'hoot'] },
      { character: '🦇', name: 'bat', keywords: ['animal', 'nature', 'blind', 'vampire'] },
      { character: '🐺', name: 'wolf', keywords: ['animal', 'nature', 'wild'] },
      { character: '🐗', name: 'boar', keywords: ['animal', 'nature'] },
      { character: '🐴', name: 'horse face', keywords: ['animal', 'brown', 'nature'] },
      { character: '🦄', name: 'unicorn', keywords: ['animal', 'nature', 'mystical'] },
      { character: '🐝', name: 'honeybee', keywords: ['animal', 'insect', 'nature', 'bug', 'spring', 'honey'] },
      { character: '🐛', name: 'bug', keywords: ['animal', 'insect', 'nature', 'worm'] },
      { character: '🦋', name: 'butterfly', keywords: ['animal', 'insect', 'nature', 'caterpillar'] },
      { character: '🐌', name: 'snail', keywords: ['slow', 'animal', 'shell'] },
      { character: '🐞', name: 'lady beetle', keywords: ['animal', 'insect', 'nature', 'ladybird'] },
      { character: '🐜', name: 'ant', keywords: ['animal', 'insect', 'nature', 'bug'] },
      { character: '🦟', name: 'mosquito', keywords: ['animal', 'nature', 'insect', 'malaria'] },
      { character: '🦗', name: 'cricket', keywords: ['animal', 'cricket', 'chirp'] },
      { character: '🕷️', name: 'spider', keywords: ['animal', 'arachnid'] },
      { character: '🕸️', name: 'spider web', keywords: ['animal', 'insect', 'arachnid', 'silk'] },
      { character: '🦂', name: 'scorpion', keywords: ['animal', 'arachnid'] },
      { character: '🐢', name: 'turtle', keywords: ['animal', 'slow', 'nature', 'tortoise'] },
      { character: '🐍', name: 'snake', keywords: ['animal', 'evil', 'nature', 'hiss', 'python'] },
      { character: '🦎', name: 'lizard', keywords: ['animal', 'nature', 'reptile'] },
      { character: '🦖', name: 'T-Rex', keywords: ['animal', 'nature', 'dinosaur', 'tyrannosaurus', 'extinct'] },
      { character: '🦕', name: 'sauropod', keywords: ['animal', 'nature', 'dinosaur', 'brontosaurus', 'extinct'] },
      { character: '🐙', name: 'octopus', keywords: ['animal', 'creature', 'ocean', 'sea', 'nature', 'beach'] },
      { character: '🦑', name: 'squid', keywords: ['animal', 'nature', 'ocean', 'sea'] },
      { character: '🦐', name: 'shrimp', keywords: ['animal', 'ocean', 'nature', 'seafood'] },
      { character: '🦞', name: 'lobster', keywords: ['animal', 'nature', 'bisque', 'claws', 'seafood'] },
      { character: '🦀', name: 'crab', keywords: ['animal', 'crustacean'] },
      { character: '🐡', name: 'blowfish', keywords: ['animal', 'nature', 'food', 'sea', 'ocean'] },
      { character: '🐠', name: 'tropical fish', keywords: ['animal', 'swim', 'ocean', 'beach', 'nemo'] },
      { character: '🐟', name: 'fish', keywords: ['animal', 'food', 'nature'] },
      { character: '🐬', name: 'dolphin', keywords: ['animal', 'nature', 'fish', 'sea', 'ocean', 'flipper', 'fins', 'beach'] },
      { character: '🐳', name: 'spouting whale', keywords: ['animal', 'nature', 'sea', 'ocean'] },
      { character: '🐋', name: 'whale', keywords: ['animal', 'nature', 'sea', 'ocean'] },
      { character: '🦈', name: 'shark', keywords: ['animal', 'nature', 'fish', 'sea', 'ocean', 'jaws', 'fins', 'beach'] },
      { character: '🐊', name: 'crocodile', keywords: ['animal', 'nature', 'reptile', 'lizard', 'alligator'] },
      { character: '🐅', name: 'tiger', keywords: ['animal', 'nature', 'roar'] },
      { character: '🐆', name: 'leopard', keywords: ['animal', 'nature'] },
      { character: '🦓', name: 'zebra', keywords: ['animal', 'nature', 'stripes', 'safari'] },
      { character: '🦍', name: 'gorilla', keywords: ['animal', 'nature', 'circus'] },
      { character: '🦧', name: 'orangutan', keywords: ['animal', 'nature'] },
      { character: '🐘', name: 'elephant', keywords: ['animal', 'nature', 'nose', 'th', 'circus'] },
      { character: '🦣', name: 'mammoth', keywords: ['animal', 'nature', 'extinct'] },
      { character: '🦏', name: 'rhinoceros', keywords: ['animal', 'nature', 'horn'] },
      { character: '🦛', name: 'hippopotamus', keywords: ['animal', 'nature'] },
      { character: '🐪', name: 'camel', keywords: ['animal', 'hot', 'desert', 'hump'] },
      { character: '🐫', name: 'two-hump camel', keywords: ['animal', 'nature', 'hot', 'desert', 'hump'] },
      { character: '🦒', name: 'giraffe', keywords: ['animal', 'nature', 'spots', 'safari'] },
      { character: '🦘', name: 'kangaroo', keywords: ['animal', 'nature', 'australia', 'joey', 'hop', 'marsupial'] },
      { character: '🦬', name: 'bison', keywords: ['animal', 'nature', 'beef', 'ox'] },
      { character: '🐃', name: 'water buffalo', keywords: ['animal', 'nature', 'ox', 'cow'] },
      { character: '🐂', name: 'ox', keywords: ['animal', 'cow', 'beef'] },
      { character: '🐄', name: 'cow', keywords: ['beef', 'ox', 'animal', 'nature', 'moo', 'milk'] },
      { character: '🐎', name: 'horse', keywords: ['animal', 'gamble', 'luck'] },
      { character: '🐖', name: 'pig', keywords: ['animal', 'nature'] },
      { character: '🐏', name: 'ram', keywords: ['animal', 'sheep', 'nature'] },
      { character: '🐑', name: 'ewe', keywords: ['animal', 'nature', 'wool', 'shipit'] },
      { character: '🦙', name: 'llama', keywords: ['animal', 'nature', 'alpaca'] },
      { character: '🐐', name: 'goat', keywords: ['animal', 'nature'] },
      { character: '🦌', name: 'deer', keywords: ['animal', 'nature', 'horns', 'venison'] },
      { character: '🐕', name: 'dog', keywords: ['animal', 'nature', 'friend', 'doge', 'pet', 'faithful'] },
      { character: '🐩', name: 'poodle', keywords: ['dog', 'animal', ' 101', 'nature', 'pet'] },
      { character: '🦮', name: 'guide dog', keywords: ['animal', 'blind', 'accessibility'] },
      { character: '🐕‍🦺', name: 'service dog', keywords: ['animal', 'accessibility'] },
      { character: '🐈', name: 'cat', keywords: ['animal', 'meow', 'nature', 'pet', 'kitten'] },
      { character: '🐈‍⬛', name: 'black cat', keywords: ['animal', 'luck', 'superstition', 'black'] },
      { character: '🐓', name: 'rooster', keywords: ['animal', 'nature', 'chicken'] },
      { character: '🦃', name: 'turkey', keywords: ['animal', 'bird'] },
      { character: '🦤', name: 'dodo', keywords: ['animal', 'bird', 'extinct'] },
      { character: '🦚', name: 'peacock', keywords: ['animal', 'nature', 'peahen'] },
      { character: '🦜', name: 'parrot', keywords: ['animal', 'nature', 'bird', 'pirate', 'talk'] },
      { character: '🦢', name: 'swan', keywords: ['animal', 'nature', 'bird'] },
      { character: '🦩', name: 'flamingo', keywords: ['animal', 'nature', 'bird', 'pink', 'tropical'] },
      { character: '🕊️', name: 'dove', keywords: ['animal', 'bird', 'peace', 'fly'] },
      { character: '🐇', name: 'rabbit', keywords: ['animal', 'nature', 'pet', 'magic', 'spring'] },
      { character: '🦝', name: 'raccoon', keywords: ['animal', 'nature'] },
      { character: '🦨', name: 'skunk', keywords: ['animal', 'nature', 'spray'] },
      { character: '🦡', name: 'badger', keywords: ['animal', 'nature', 'honey'] },
      { character: '🦔', name: 'hedgehog', keywords: ['animal', 'nature', 'spiny'] },
      { character: '🦦', name: 'otter', keywords: ['animal', 'nature'] },
      { character: '🦥', name: 'sloth', keywords: ['animal', 'nature', 'slow', 'lazy'] },
      { character: '🐁', name: 'mouse', keywords: ['animal', 'nature', 'rodent'] },
      { character: '🐀', name: 'rat', keywords: ['animal', 'mouse', 'rodent'] },
      { character: '🐿️', name: 'chipmunk', keywords: ['animal', 'nature', 'rodent', 'squirrel'] },
      { character: '🦔', name: 'hedgehog', keywords: ['animal', 'nature', 'spiny'] }
    ],
    food: [
      { character: '🍏', name: 'green apple', keywords: ['fruit', 'nature'] },
      { character: '🍎', name: 'red apple', keywords: ['fruit', 'mac', 'school'] },
      { character: '🍐', name: 'pear', keywords: ['fruit', 'nature', 'food'] },
      { character: '🍊', name: 'tangerine', keywords: ['food', 'fruit', 'nature', 'orange'] },
      { character: '🍋', name: 'lemon', keywords: ['fruit', 'nature'] },
      { character: '🍌', name: 'banana', keywords: ['fruit', 'food', 'monkey'] },
      { character: '🍉', name: 'watermelon', keywords: ['fruit', 'food', 'picnic', 'summer'] },
      { character: '🍇', name: 'grapes', keywords: ['fruit', 'food', 'wine'] },
      { character: '🍓', name: 'strawberry', keywords: ['fruit', 'food', 'nature'] },
      { character: '🫐', name: 'blueberries', keywords: ['fruit', 'food', 'berry'] },
      { character: '🍈', name: 'melon', keywords: ['fruit', 'nature', 'food'] },
      { character: '🍒', name: 'cherries', keywords: ['fruit', 'food', 'cherry'] },
      { character: '🍑', name: 'peach', keywords: ['fruit', 'nature', 'food'] },
      { character: '🥭', name: 'mango', keywords: ['fruit', 'food', 'tropical'] },
      { character: '🍍', name: 'pineapple', keywords: ['fruit', 'nature', 'food'] },
      { character: '🥥', name: 'coconut', keywords: ['fruit', 'nature', 'food', 'palm'] },
      { character: '🥝', name: 'kiwi fruit', keywords: ['fruit', 'food'] },
      { character: '🍅', name: 'tomato', keywords: ['fruit', 'vegetable', 'nature', 'food'] },
      { character: '🍆', name: 'eggplant', keywords: ['vegetable', 'nature', 'food', 'aubergine'] },
      { character: '🥑', name: 'avocado', keywords: ['fruit', 'food'] },
      { character: '🥦', name: 'broccoli', keywords: ['fruit', 'food', 'vegetable'] },
      { character: '🥬', name: 'leafy greens', keywords: ['vegetable', 'food', 'lettuce'] },
      { character: '🥒', name: 'cucumber', keywords: ['fruit', 'food', 'pickle'] },
      { character: '🌶️', name: 'hot pepper', keywords: ['food', 'spicy', 'chilli', 'chili'] },
      { character: '🫑', name: 'bell pepper', keywords: ['fruit', 'plant'] },
      { character: '🌽', name: 'ear of corn', keywords: ['food', 'vegetable', 'plant'] },
      { character: '🥕', name: 'carrot', keywords: ['vegetable', 'food'] },
      { character: '🫒', name: 'olive', keywords: ['fruit', 'food'] },
      { character: '🧄', name: 'garlic', keywords: ['food', 'spice'] },
      { character: '🧅', name: 'onion', keywords: ['cook', 'food', 'spice'] },
      { character: '🥔', name: 'potato', keywords: ['food', 'tuber', 'veggie', 'starch'] },
      { character: '🍠', name: 'roasted sweet potato', keywords: ['food', 'nature'] },
      { character: '🥐', name: 'croissant', keywords: ['food', 'bread', 'french'] },
      { character: '🥯', name: 'bagel', keywords: ['food', 'bread', 'bakery', 'schmear'] },
      { character: '🍞', name: 'bread', keywords: ['food', 'wheat', 'breakfast', 'toast'] },
      { character: '🥖', name: 'baguette bread', keywords: ['food', 'bread', 'french'] },
      { character: '🥨', name: 'pretzel', keywords: ['food', 'bread', 'twisted'] },
      { character: '🧀', name: 'cheese wedge', keywords: ['food', 'chaddar'] },
      { character: '🥚', name: 'egg', keywords: ['food', 'chicken', 'breakfast'] },
      { character: '🍳', name: 'cooking', keywords: ['food', 'breakfast', 'kitchen', 'egg'] },
      { character: '🧈', name: 'butter', keywords: ['food', 'cook'] },
      { character: '🥞', name: 'pancakes', keywords: ['food', 'breakfast', 'flapjacks', 'hotcakes'] },
      { character: '🧇', name: 'waffle', keywords: ['food', 'breakfast', 'kitchen'] },
      { character: '🥓', name: 'bacon', keywords: ['food', 'breakfast', 'pork', 'pig', 'meat'] },
      { character: '🥩', name: 'cut of meat', keywords: ['food', 'cow', 'meat', 'cut', 'chop', 'lambchop', 'porkchop'] },
      { character: '🍗', name: 'poultry leg', keywords: ['food', 'meat', 'drumstick', 'bird', 'chicken', 'turkey'] },
      { character: '🍖', name: 'meat on bone', keywords: ['good', 'food', 'drumstick'] },
      { character: '🦴', name: 'bone', keywords: ['skeleton'] },
      { character: '🌭', name: 'hot dog', keywords: ['food', 'frankfurter'] },
      { character: '🍔', name: 'hamburger', keywords: ['meat', 'fast food', 'beef', 'cheeseburger', 'mcdonalds', 'burger king'] },
      { character: '🍟', name: 'french fries', keywords: ['chips', 'snack', 'fast food'] },
      { character: '🍕', name: 'pizza', keywords: ['food', 'party'] },
      { character: '🥙', name: 'stuffed flatbread', keywords: ['food', 'flatbread', 'stuffed', 'gyro'] },
      { character: '🌮', name: 'taco', keywords: ['food', 'mexican'] },
      { character: '🌯', name: 'burrito', keywords: ['food', 'mexican'] },
      { character: '🫔', name: 'tamale', keywords: ['food', 'mexican'] },
      { character: '🥗', name: 'green salad', keywords: ['food', 'healthy', 'lettuce'] },
      { character: '🥘', name: 'shallow pan of food', keywords: ['food', 'cooking', 'casserole', 'paella'] },
      { character: '🫕', name: 'fondue', keywords: ['food', 'cheese', 'pot'] },
      { character: '🥫', name: 'canned food', keywords: ['food', 'soup'] },
      { character: '🍝', name: 'spaghetti', keywords: ['food', 'italian', 'noodle'] },
      { character: '🍜', name: 'steaming bowl', keywords: ['food', 'japanese', 'noodle', 'chopsticks', 'ramen'] },
      { character: '🍲', name: 'pot of food', keywords: ['food', 'meat', 'soup'] },
      { character: '🍛', name: 'curry rice', keywords: ['food', 'spicy', 'hot', 'indian'] },
      { character: '🍣', name: 'sushi', keywords: ['food', 'fish', 'japanese', 'rice'] },
      { character: '🍱', name: 'bento box', keywords: ['food', 'japanese', 'box'] },
      { character: '🥟', name: 'dumpling', keywords: ['food', 'empanada', 'pierogi', 'potsticker'] },
      { character: '🦪', name: 'oyster', keywords: ['food', 'diving', 'pearl'] },
      { character: '🍤', name: 'fried shrimp', keywords: ['food', 'animal', 'appetizer', 'summer'] },
      { character: '🍙', name: 'rice ball', keywords: ['food', 'japanese'] },
      { character: '🍚', name: 'cooked rice', keywords: ['food', 'china', 'asian'] },
      { character: '🍘', name: 'rice cracker', keywords: ['food', 'japanese'] },
      { character: '🍥', name: 'fish cake with swirl', keywords: ['food', 'japan', 'sea', 'beach', 'narutomaki', 'pink', 'swirl', 'kamaboko', 'surimi', 'ramen'] },
      { character: '🥠', name: 'fortune cookie', keywords: ['food', 'prophecy'] },
      { character: '🥮', name: 'moon cake', keywords: ['food', 'autumn'] },
      { character: '🍢', name: 'oden', keywords: ['food', 'japanese'] },
      { character: '🍡', name: 'dango', keywords: ['food', 'dessert', 'sweet', 'japanese', 'barbecue', 'meat'] },
      { character: '🍧', name: 'shaved ice', keywords: ['hot', 'dessert', 'summer'] },
      { character: '🍨', name: 'ice cream', keywords: ['food', 'hot', 'dessert'] },
      { character: '🍦', name: 'soft ice cream', keywords: ['food', 'hot', 'dessert', 'summer'] },
      { character: '🥧', name: 'pie', keywords: ['food', 'dessert', 'pastry'] },
      { character: '🧁', name: 'cupcake', keywords: ['food', 'dessert', 'cake'] },
      { character: '🍰', name: 'shortcake', keywords: ['food', 'dessert'] },
      { character: '🎂', name: 'birthday cake', keywords: ['food', 'dessert', 'cake'] },
      { character: '🍮', name: 'custard', keywords: ['dessert', 'food'] },
      { character: '🍭', name: 'lollipop', keywords: ['food', 'dessert', 'candy', 'sweet', 'sugar'] },
      { character: '🍬', name: 'candy', keywords: ['snack', 'dessert', 'sweet', 'lolly'] },
      { character: '🍫', name: 'chocolate bar', keywords: ['food', 'snack', 'dessert', 'sweet'] },
      { character: '🍿', name: 'popcorn', keywords: ['food', 'movie theater', 'films', 'snack'] },
      { character: '🍩', name: 'doughnut', keywords: ['food', 'dessert', 'snack', 'sweet', 'donut'] },
      { character: '🍪', name: 'cookie', keywords: ['food', 'snack', 'oreo', 'chocolate', 'sweet', 'dessert'] }
    ],
    travel: [
      { character: '🚗', name: 'car', keywords: ['automobile', 'red'] },
      { character: '🚕', name: 'taxi', keywords: ['uber', 'vehicle', 'cars', 'transportation'] },
      { character: '🚙', name: 'sport utility vehicle', keywords: ['transportation', 'vehicle'] },
      { character: '🚌', name: 'bus', keywords: ['car', 'vehicle', 'transportation'] },
      { character: '🚎', name: 'trolleybus', keywords: ['bart', 'transportation', 'vehicle'] },
      { character: '🏎️', name: 'racing car', keywords: ['sports', 'race', 'fast', 'formula', 'f1'] },
      { character: '🚓', name: 'police car', keywords: ['vehicle', 'cars', 'transportation', 'law', 'legal', 'enforcement'] },
      { character: '🚑', name: 'ambulance', keywords: ['health', ' 911', 'hospital'] },
      { character: '🚒', name: 'fire engine', keywords: ['transportation', 'cars', 'vehicle'] },
      { character: '🚐', name: 'minibus', keywords: ['vehicle', 'car', 'transportation'] },
      { character: '🛻', name: 'pickup truck', keywords: ['car', 'transportation'] },
      { character: '🚚', name: 'delivery truck', keywords: ['cars', 'transportation'] },
      { character: '🚛', name: 'articulated lorry', keywords: ['vehicle', 'cars', 'transportation', 'express'] },
      { character: '🚜', name: 'tractor', keywords: ['transportation', 'vehicle'] },
      { character: '🏍️', name: 'motorcycle', keywords: ['race', 'sports', 'fast'] },
      { character: '🛵', name: 'motor scooter', keywords: ['vehicle', 'vespa', 'sasha'] },
      { character: '🚲', name: 'bicycle', keywords: ['sports', 'bicycle', 'exercise', 'hipster'] },
      { character: '🛴', name: 'kick scooter', keywords: ['vehicle', 'kick', 'razor'] },
      { character: '🛹', name: 'skateboard', keywords: ['board'] },
      { character: '🛼', name: 'roller skate', keywords: ['footwear', 'sports'] },
      { character: '🚁', name: 'helicopter', keywords: ['transportation', 'vehicle', 'fly'] },
      { character: '🛸', name: 'flying saucer', keywords: ['transportation', 'vehicle', 'ufo'] },
      { character: '✈️', name: 'airplane', keywords: ['vehicle', 'transportation', 'fly', 'jet'] },
      { character: '🛩️', name: 'small airplane', keywords: ['flight', 'transportation', 'fly', 'vehicle'] },
      { character: '🛫', name: 'airplane departure', keywords: ['transportation', 'vehicle', 'fly'] },
      { character: '🛬', name: 'airplane arrival', keywords: ['transportation', 'vehicle', 'fly'] },
      { character: '🪂', name: 'parachute', keywords: ['flight', 'fly'] },
      { character: '💺', name: 'seat', keywords: ['sit', 'airplane', 'transport', 'bus', 'flight', 'fly'] },
      { character: '🚀', name: 'rocket', keywords: ['launch', 'ship', 'staffmode', 'NASA', 'outer space', 'outer_space', 'fly'] },
      { character: '🛰️', name: 'satellite', keywords: ['communication', 'future', 'radio', 'space'] },
      { character: '🚢', name: 'ship', keywords: ['transportation', 'titanic', 'deploy'] },
      { character: '⛵', name: 'sailboat', keywords: ['ship', 'summer', 'transportation', 'water', 'sailing'] },
      { character: '🚤', name: 'speedboat', keywords: ['ship', 'transportation', 'vehicle', 'summer'] },
      { character: '⛴️', name: 'ferry', keywords: ['boat', 'ship', 'yacht'] },
      { character: '🛳️', name: 'passenger ship', keywords: ['yacht', 'cruise', 'boat'] },
      { character: '🚁', name: 'helicopter', keywords: ['transportation', 'vehicle', 'fly'] },
      { character: '🚂', name: 'locomotive', keywords: ['transportation', 'vehicle'] },
      { character: '🚆', name: 'train', keywords: ['transportation', 'vehicle'] },
      { character: '🚄', name: 'high-speed train', keywords: ['transportation', 'vehicle'] },
      { character: '🚅', name: 'bullet train', keywords: ['transportation', 'vehicle', 'speed', 'fast', 'public'] },
      { character: '🚈', name: 'light rail', keywords: ['transportation', 'vehicle'] },
      { character: '🚝', name: 'monorail', keywords: ['transportation', 'vehicle'] },
      { character: '🚞', name: 'mountain railway', keywords: ['transportation', 'vehicle'] },
      { character: '🚋', name: 'tram car', keywords: ['transportation', 'vehicle'] },
      { character: '🚃', name: 'railway car', keywords: ['transportation', 'vehicle'] },
      { character: '🚟', name: 'suspension railway', keywords: ['vehicle', 'transportation'] },
      { character: '🚠', name: 'mountain cableway', keywords: ['transportation', 'vehicle', 'ski'] },
      { character: '🚡', name: 'aerial tramway', keywords: ['transportation', 'vehicle', 'ski'] },
      { character: '🚊', name: 'tram', keywords: ['transportation', 'vehicle'] },
      { character: '🚉', name: 'station', keywords: ['transportation', 'vehicle', 'public'] },
      { character: '🚇', name: 'metro', keywords: ['transportation', 'blue-square', 'mrt', 'underground', 'tube'] },
      { character: '🚍', name: 'oncoming bus', keywords: ['vehicle', 'transportation'] },
      { character: '🚘', name: 'oncoming automobile', keywords: ['car', 'vehicle', 'transportation'] },
      { character: '🚖', name: 'oncoming taxi', keywords: ['vehicle', 'cars', 'uber'] },
      { character: '🚔', name: 'oncoming police car', keywords: ['vehicle', 'law', 'legal', 'enforcement', 'police'] },
      { character: '🚨', name: 'police car light', keywords: ['police', 'ambulance', 'warning', 'cars', 'urgent'] }
    ],
    objects: [
      { character: '⌚', name: 'watch', keywords: ['time', 'accessories'] },
      { character: '📱', name: 'mobile phone', keywords: ['technology', 'apple', 'gadgets', 'dial'] },
      { character: '📲', name: 'mobile phone with arrow', keywords: ['iphone', 'incoming'] },
      { character: '💻', name: 'laptop computer', keywords: ['technology', 'laptop', 'screen', 'display', 'monitor'] },
      { character: '⌨️', name: 'keyboard', keywords: ['technology', 'computer', 'type', 'input', 'text'] },
      { character: '🖥️', name: 'desktop computer', keywords: ['technology', 'computing', 'screen'] },
      { character: '🖨️', name: 'printer', keywords: ['paper', 'ink'] },
      { character: '🖱️', name: 'computer mouse', keywords: ['click'] },
      { character: '🖲️', name: 'trackball', keywords: ['technology', 'trackpad'] },
      { character: '🕹️', name: 'joystick', keywords: ['game', 'play'] },
      { character: '🗜️', name: 'clamp', keywords: ['tool'] },
      { character: '💽', name: 'computer disk', keywords: ['technology', 'record', 'data', '90s'] },
      { character: '💾', name: 'floppy disk', keywords: ['oldschool', 'technology', 'save', '90s', 'disk'] },
      { character: '💿', name: 'optical disk', keywords: ['technology', 'dvd', 'disk', 'disc', '90s'] },
      { character: '📀', name: 'dvd', keywords: ['cd', 'disk', 'disc'] },
      { character: '📼', name: 'videocassette', keywords: ['record', 'video', 'oldschool', '90s', 'cassette'] },
      { character: '📷', name: 'camera', keywords: ['gadgets', 'photography'] },
      { character: '📸', name: 'camera with flash', keywords: ['photography', 'gadgets'] },
      { character: '📹', name: 'video camera', keywords: ['film', 'record'] },
      { character: '🎥', name: 'movie camera', keywords: ['film', 'record'] },
      { character: '📽️', name: 'film projector', keywords: ['video', 'tape', 'record', 'movie'] },
      { character: '🎞️', name: 'film frames', keywords: ['movie'] },
      { character: '📞', name: 'telephone receiver', keywords: ['technology', 'communication', 'dial'] },
      { character: '☎️', name: 'telephone', keywords: ['technology', 'communication', 'dial', 'telephone'] },
      { character: '📟', name: 'pager', keywords: ['communication', '90s'] },
      { character: '📠', name: 'fax machine', keywords: ['communication', 'technology'] },
      { character: '📺', name: 'television', keywords: ['technology', 'program', 'oldschool', 'show', 'television'] },
      { character: '📻', name: 'radio', keywords: ['communication', 'music', 'podcast', 'program'] },
      { character: '🎙️', name: 'studio microphone', keywords: ['singer', 'recording', 'artist', 'talkshow'] },
      { character: '🎚️', name: 'level slider', keywords: ['scale'] },
      { character: '🎛️', name: 'control knobs', keywords: ['dial'] },
      { character: '🧭', name: 'compass', keywords: ['magnetic', 'navigation', 'orienteering'] },
      { character: '⏱️', name: 'stopwatch', keywords: ['time', 'deadline'] },
      { character: '⏲️', name: 'timer clock', keywords: ['time', 'deadline'] },
      { character: '⏰', name: 'alarm clock', keywords: ['time', 'wake'] },
      { character: '🕰️', name: 'mantelpiece clock', keywords: ['time'] },
      { character: '⌛', name: 'hourglass done', keywords: ['time', 'clock', 'oldschool', 'limit', 'exam', 'quiz', 'test'] },
      { character: '⏳', name: 'hourglass not done', keywords: ['oldschool', 'time', 'countdown'] },
      { character: '📡', name: 'satellite antenna', keywords: ['communication', 'future', 'radio', 'space'] },
      { character: '🔋', name: 'battery', keywords: ['power', 'energy', 'sustain'] },
      { character: '🔌', name: 'electric plug', keywords: ['charger', 'power'] },
      { character: '💡', name: 'light bulb', keywords: ['light', 'electricity', 'idea'] },
      { character: '🔦', name: 'flashlight', keywords: ['dark', 'camping', 'sight', 'night'] },
      { character: '🕯️', name: 'candle', keywords: ['fire', 'wax'] },
      { character: '🪔', name: 'diya lamp', keywords: ['fire', 'lamp'] },
      { character: '🧯', name: 'fire extinguisher', keywords: ['fire'] },
      { character: '🛢️', name: 'oil drum', keywords: ['barrell'] },
      { character: '💸', name: 'money with wings', keywords: ['dollar', 'bills', 'payment', 'sale'] },
      { character: '💵', name: 'dollar banknote', keywords: ['money', 'sales', 'bill', 'currency'] },
      { character: '💴', name: 'yen banknote', keywords: ['money', 'sales', 'japanese', 'dollar', 'currency'] },
      { character: '💶', name: 'euro banknote', keywords: ['money', 'sales', 'dollar', 'currency'] },
      { character: '💷', name: 'pound banknote', keywords: ['british', 'sterling', 'money', 'sales', 'bills', 'uk', 'england', 'currency'] }
    ],
    symbols: [
      { character: '❤️', name: 'red heart', keywords: ['love', 'like', 'valentines'] },
      { character: '🧡', name: 'orange heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💛', name: 'yellow heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💚', name: 'green heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💙', name: 'blue heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💜', name: 'purple heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '🖤', name: 'black heart', keywords: ['evil'] },
      { character: '🤍', name: 'white heart', keywords: ['pure'] },
      { character: '🤎', name: 'brown heart', keywords: ['coffee'] },
      { character: '💔', name: 'broken heart', keywords: ['sad', 'sorry', 'break', 'heart', 'heartbreak'] },
      { character: '❣️', name: 'heart exclamation', keywords: ['decoration', 'love'] },
      { character: '💕', name: 'two hearts', keywords: ['love', 'like', 'affection', 'valentines', 'heart'] },
      { character: '💞', name: 'revolving hearts', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💓', name: 'beating heart', keywords: ['love', 'like', 'affection', 'valentines', 'pink', 'heart'] },
      { character: '💗', name: 'growing heart', keywords: ['like', 'love', 'affection', 'valentines', 'pink'] },
      { character: '💖', name: 'sparkling heart', keywords: ['love', 'like', 'affection', 'valentines'] },
      { character: '💘', name: 'heart with arrow', keywords: ['love', 'like', 'heart', 'affection', 'valentines'] },
      { character: '💝', name: 'heart with ribbon', keywords: ['love', 'valentines'] },
      { character: '💟', name: 'heart decoration', keywords: ['purple-square', 'love', 'like'] },
      { character: '☮️', name: 'peace symbol', keywords: ['hippie'] },
      { character: '✝️', name: 'latin cross', keywords: ['christianity'] },
      { character: '☪️', name: 'star and crescent', keywords: ['islam'] },
      { character: '🕉️', name: 'om', keywords: ['hinduism', 'buddhism', 'sikhism', 'jainism'] },
      { character: '☸️', name: 'wheel of dharma', keywords: ['hinduism', 'buddhism', 'sikhism', 'jainism'] },
      { character: '✡️', name: 'star of David', keywords: ['judaism'] },
      { character: '🔯', name: 'dotted six-pointed star', keywords: ['purple-square', 'religion', 'jewish', 'hexagram'] },
      { character: '🕎', name: 'menorah', keywords: ['hanukkah', 'candles', 'jewish'] },
      { character: '☯️', name: 'yin yang', keywords: ['balance'] },
      { character: '☦️', name: 'orthodox cross', keywords: ['suppedaneum', 'religion'] },
      { character: '🛐', name: 'place of worship', keywords: ['religion', 'church', 'temple', 'prayer'] },
      { character: '⛎', name: 'Ophiuchus', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♈', name: 'Aries', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♉', name: 'Taurus', keywords: ['purple-square', 'sign', 'constellation', 'astrology'] },
      { character: '♊', name: 'Gemini', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♋', name: 'Cancer', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♌', name: 'Leo', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♍', name: 'Virgo', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♎', name: 'Libra', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♏', name: 'Scorpio', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♐', name: 'Sagittarius', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♑', name: 'Capricorn', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♒', name: 'Aquarius', keywords: ['sign', 'purple-square', 'constellation', 'astrology'] },
      { character: '♓', name: 'Pisces', keywords: ['purple-square', 'sign', 'constellation', 'astrology'] },
      { character: '🆔', name: 'ID button', keywords: ['purple-square', 'words'] },
      { character: '⚛️', name: 'atom symbol', keywords: ['science', 'physics', 'chemistry'] },
      { character: '🉑', name: 'Japanese "acceptable" button', keywords: ['orange-square', 'good', 'chinese', 'kanji', 'agree', 'yes', 'OK'] },
      { character: '☢️', name: 'radioactive', keywords: ['nuclear', 'danger'] },
      { character: '☣️', name: 'biohazard', keywords: ['danger'] },
      { character: '📴', name: 'mobile phone off', keywords: ['mute', 'orange-square', 'silence', 'quiet'] },
      { character: '📳', name: 'vibration mode', keywords: ['orange-square', 'phone'] },
      { character: '🈶', name: 'Japanese "not free of charge" button', keywords: ['orange-square', 'chinese', 'japanese', 'kanji'] },
      { character: '🈚', name: 'Japanese "free of charge" button', keywords: ['orange-square', 'chinese', 'japanese', 'kanji'] },
      { character: '🈸', name: 'Japanese "application" button', keywords: ['orange-square', 'chinese', 'japanese', 'kanji'] },
      { character: '🈺', name: 'Japanese "open for business" button', keywords: ['orange-square', 'chinese', 'japanese', 'kanji'] },
      { character: '🈷️', name: 'Japanese "monthly amount" button', keywords: ['orange-square', 'chinese', 'japanese', 'kanji'] },
      { character: '✴️', name: 'eight-pointed star', keywords: ['orange-square', 'shape', 'polygon'] },
      { character: '🆚', name: 'VS button', keywords: ['orange-square', 'words'] },
      { character: '💮', name: 'white flower', keywords: ['japanese', 'spring'] },
      { character: '🉐', name: 'Japanese "bargain" button', keywords: ['chinese', 'kanji', 'obtain', 'get', 'circle'] },
      { character: '㊙️', name: 'Japanese "secret" button', keywords: ['privacy', 'chinese', 'sshh', 'kanji', 'red-circle'] },
      { character: '㊗️', name: 'Japanese "congratulations" button', keywords: ['chinese', 'kanji', 'japanese', 'red-circle'] },
      { character: '🈴', name: 'Japanese "passing grade" button', keywords: ['chinese', 'japanese', 'kanji', 'red-square'] },
      { character: '🈵', name: 'Japanese "no vacancy" button', keywords: ['chinese', 'japanese', 'kanji', 'red-square'] },
      { character: '🈹', name: 'Japanese "discount" button', keywords: ['chinese', 'kanji', 'japanese', 'red-square'] },
      { character: '🈲', name: 'Japanese "prohibited" button', keywords: ['kanji', 'japanese', 'chinese', 'forbidden', 'limit', 'restricted', 'red-square'] }
    ],
    flags: [
      { character: '🏁', name: 'chequered flag', keywords: ['contest', 'finishline', 'race', 'gokart'] },
      { character: '🚩', name: 'triangular flag', keywords: ['mark', 'milestone', 'place'] },
      { character: '🎌', name: 'crossed flags', keywords: ['japanese', 'nation', 'country', 'border'] },
      { character: '🏴', name: 'black flag', keywords: ['pirate'] },
      { character: '🏳️', name: 'white flag', keywords: ['losing', 'loser', 'lost', 'surrender', 'give up', 'fail'] },
      { character: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride', 'gay', 'lgbt', 'glbt', 'queer', 'homosexual', 'lesbian', 'bisexual', 'transgender'] },
      { character: '🏳️‍⚧️', name: 'transgender flag', keywords: ['lgbtq', 'transgender'] },
      { character: '🏴‍☠️', name: 'pirate flag', keywords: ['skull', 'crossbones', 'pirate'] },
      { character: '🇺🇸', name: 'flag: United States', keywords: ['united', 'states', 'america', 'freedom', 'nation', 'country', 'banner'] },
      { character: '🇬🇧', name: 'flag: United Kingdom', keywords: ['united', 'kingdom', 'great', 'britain', 'northern', 'ireland', 'uk', 'england', 'union jack'] },
      { character: '🇨🇦', name: 'flag: Canada', keywords: ['ca', 'flag'] },
      { character: '🇦🇺', name: 'flag: Australia', keywords: ['au', 'flag'] },
      { character: '🇯🇵', name: 'flag: Japan', keywords: ['jp', 'flag'] },
      { character: '🇰🇷', name: 'flag: South Korea', keywords: ['kr', 'flag'] },
      { character: '🇩🇪', name: 'flag: Germany', keywords: ['de', 'flag'] },
      { character: '🇫🇷', name: 'flag: France', keywords: ['fr', 'banner', 'flag'] },
      { character: '🇪🇸', name: 'flag: Spain', keywords: ['es', 'flag'] },
      { character: '🇮🇹', name: 'flag: Italy', keywords: ['it', 'flag'] },
      { character: '🇷🇺', name: 'flag: Russia', keywords: ['ru', 'flag'] },
      { character: '🇨🇳', name: 'flag: China', keywords: ['china', 'prc', 'flag'] },
      { character: '🇮🇳', name: 'flag: India', keywords: ['in', 'flag'] },
      { character: '🇧🇷', name: 'flag: Brazil', keywords: ['br', 'flag'] },
      { character: '🇲🇽', name: 'flag: Mexico', keywords: ['mx', 'flag'] },
      { character: '🇦🇷', name: 'flag: Argentina', keywords: ['ar', 'flag'] },
      { character: '🇿🇦', name: 'flag: South Africa', keywords: ['south', 'africa', 'flag'] },
      { character: '🇪🇬', name: 'flag: Egypt', keywords: ['eg', 'flag'] },
      { character: '🇳🇬', name: 'flag: Nigeria', keywords: ['flag'] },
      { character: '🇸🇦', name: 'flag: Saudi Arabia', keywords: ['flag'] },
      { character: '🇹🇷', name: 'flag: Turkey', keywords: ['tr', 'flag'] },
      { character: '🇮🇷', name: 'flag: Iran', keywords: ['ir', 'flag'] },
      { character: '🇮🇱', name: 'flag: Israel', keywords: ['il', 'flag'] },
      { character: '🇦🇪', name: 'flag: United Arab Emirates', keywords: ['united', 'arab', 'emirates', 'flag'] },
      { character: '🇹🇭', name: 'flag: Thailand', keywords: ['th', 'flag'] },
      { character: '🇻🇳', name: 'flag: Vietnam', keywords: ['vn', 'flag'] },
      { character: '🇸🇬', name: 'flag: Singapore', keywords: ['sg', 'flag'] },
      { character: '🇲🇾', name: 'flag: Malaysia', keywords: ['my', 'flag'] },
      { character: '🇵🇭', name: 'flag: Philippines', keywords: ['ph', 'flag'] },
      { character: '🇮🇩', name: 'flag: Indonesia', keywords: ['id', 'flag'] },
      { character: '🇧🇩', name: 'flag: Bangladesh', keywords: ['bd', 'flag'] },
      { character: '🇵🇰', name: 'flag: Pakistan', keywords: ['pk', 'flag'] }
    ]
  };

  private categoryConfig = [
    { name: 'Smileys', icon: '😀' },
    { name: 'People', icon: '👋' },
    { name: 'Animals', icon: '🐶' },
    { name: 'Food', icon: '🍏' },
    { name: 'Travel', icon: '🚗' },
    { name: 'Objects', icon: '⌚' },
    { name: 'Symbols', icon: '❤️' },
    { name: 'Flags', icon: '🏁' }
  ];

  async loadEmojis(): Promise<void> {
    if (this.isLoaded) return;

    // Process offline emoji database
    this.categories = this.categoryConfig.map(config => {
      const categoryKey = Object.keys(this.emojiDatabase).find(key => 
        key.includes(config.name.toLowerCase()) || 
        config.name.toLowerCase().includes(key.split('-')[0])
      );
      
      const emojis = categoryKey ? this.emojiDatabase[categoryKey] : [];
      
      return {
        name: config.name,
        icon: config.icon,
        emojis
      };
    }).filter(category => category.emojis.length > 0);

    this.isLoaded = true;
  }

  getCategories(): EmojiCategory[] {
    return this.categories;
  }

  searchEmojis(query: string): EmojiData[] {
    if (!query.trim()) return [];

    const searchTerm = query.toLowerCase();
    const allEmojis = this.categories.flatMap(cat => cat.emojis);
    
    return allEmojis.filter(emoji => 
      emoji.name.toLowerCase().includes(searchTerm) ||
      emoji.keywords.some(keyword => keyword.toLowerCase().includes(searchTerm))
    ).slice(0, 40); // Show more search results
  }

  getFrequentlyUsed(): string[] {
    const stored = localStorage.getItem('frequentEmojis');
    if (stored) {
      return JSON.parse(stored);
    }
    
    // Return default popular emojis
    return ['😀', '😍', '😂', '🥰', '😊', '👍', '❤️', '🔥', '👏', '🙏', '💯', '✨', '🎉', '😎', '🤔', '😅', '🤣', '💪', '🙌', '😭'];
  }

  addToFrequentlyUsed(emoji: string): void {
    const current = this.getFrequentlyUsed();
    const filtered = current.filter(e => e !== emoji);
    const updated = [emoji, ...filtered].slice(0, 24); // Keep top 24 (3 rows of 8)
    localStorage.setItem('frequentEmojis', JSON.stringify(updated));
  }
}

export const emojiService = new EmojiService();
export type { EmojiData, EmojiCategory };